#!/bin/bash

if [ -d ~/".dotfiles_backup" ]; then
	:
else
	mkdir ~/".dotfiles_backup"
fi

for f in .??*
do
	[[ "$f" == ".git" ]] && continue
	[[ "$f" == ".gitignore" ]] && continue

	if [ -f ~/"$f" ] || [ -d ~/"$f" ]; then
		mv ~/"$f" ~/.dotfiles_backup/
	else
		:
	fi

	ln -s $(pwd)/$f ~/$f
done

echo -e "\nBackup move to ~/.dotfiles_backup\n"
echo "Done"
