#!/bin/bash

if [ ! -d ~/".dotfiles_backup" ]; then
  mkdir ~/".dotfiles_backup"
fi

for f in .??*
do
  [[ $f == ".git" ]] && continue
  [[ $f == ".gitignore" ]] && continue

  if [ -f ~/$f ]; then
    mv ~/$f ~/.dotfiles_backup/
    ln -s $(pwd)/$f ~/$f
  elif [ -d ~/$f ]; then
    ln -s $(pwd)/$f/* ~/$f/
  else
    ln -s $(pwd)/$f ~/$f
  fi
done

source ~/.bashrc
xmodmap ~/.xmodmap

echo -e "\nBackup move to ~/.dotfiles_backup\n"
echo -e "Done\n"
