# toml syntax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# For Markdown
[[plugins]]
repo = 'instant-markdown/vim-instant-markdown'
hook_add = '''
  source ~/.config/nvim/plugins/markdown.vim
'''
