# toml syntax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# 自動補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
  source ~/.config/nvim/plugins/deoplete.vim
'''

# coc.vim (https://dev.classmethod.jp/articles/neovim_lsp_python/)
