[[plugins]]
repo = 'Shougo/dein.vim'

# ターミナルのテーマカラー
[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
  colorscheme tender
  set background=dark
  syntax on
  set t_Co=256
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
'''

# if,do,def等のブロックのendを自動入力
[[plugins]]
repo = 'tpope/vim-endwise'

# かっこ等の閉じを自動入力
[[plugins]]
repo = 'Townk/vim-autoclose'

# コードチェックの表示
[[plugins]]
repo = 'w0rp/ale'

# gitで管理しているファイル編集時に差分を表示
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set signcolumn=yes
  set updatetime=1000
  nnoremap [gitgutter] <Nop>
  nmap <C-g> [gitgutter]
  nmap [gitgutter]j <Plug>GitGutterNextHunk
  nmap [gitgutter]k <Plug>GitGutterPrevHunk
  nmap [gitgutter]u <Plug>GitGutterUndoHunk
'''

# git操作
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  command Gst :Gstatus
  command Gdf :Gdiff
  command Gbl :Gblame
  command Gps :Gpush
  command Gpl :Gpull
'''

# 検索時にマッチ数と順番を表示
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  nmap n <Plug>(anzu-n-with-echo)
  nmap N <Plug>(anzu-N-with-echo)
  nmap * <Plug>(anzu-star)
  nmap # <Plug>(anzu-sharp)
'''

# ファイルのあいまい検索、中身の文字列検索
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  nnoremap [denite] <Nop>
  nmap <C-d> [denite]
  nnoremap <silent> [denite]g :<C-u>Denite grep -buffer-name=search-buffer-denite<CR>
  nnoremap <silent> [denite]r :<C-u>Denite -resume -buffer-name=search-buffer-denite<CR>
  nnoremap <silent> [denite]p :<C-u>Denite file_rec<CR>
  call denite#custom#var('grep','command',['pt','--follow','--nogroup','--nocolor','--hidden'])
  call denite#custom#var('grep','default_opts',[])
  call denite#custom#var('grep','recursive_opts',[])
  call denite#custom#var('file_rec','command',['pt','--follow','--nogroup','--nocolor','--hidden','-g',''])
'''
