[[plugins]]
repo = 'Shougo/dein.vim'

# ターミナルのテーマカラー
[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
  source ~/.config/nvim/plugins/tender.vim
'''

# if,do,def等のブロックのendを自動入力
[[plugins]]
repo = 'tpope/vim-endwise'

# ブラケットのペアの入力補助
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# コードチェックの表示
[[plugins]]
repo = 'w0rp/ale'

# gitで管理しているファイル編集時に差分を表示
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  source ~/.config/nvim/plugins/gitgutter.vim
'''

# git操作
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  source ~/.config/nvim/plugins/fugitive.vim
'''

# 検索時にマッチ数と順番を表示
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  source ~/.config/nvim/plugins/anzu.vim
'''

# ファイルのあいまい検索、中身の文字列検索
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/denite.vim
'''

# ファイラー
[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = '''
  source ~/.config/nvim/plugins/defx.vim
'''
